Event listeners
linqs/shark-clipper pull request #18
Opened 2024-07-02 17:21 UTC by fkurmannucsc

Stopped propagation of typing events to prevent triggering hotkeys.

2024-07-02 17:31 UTC, eriq-augustine requested changes
I'm afk most of the day, so I'll keep it terse.

Instead of putting listeners explicitly on all input fields, just attach them when initializing hotkeys.
Then init hotkeys when you add screenshots (so the new inputs also have the handlers).

This way, we have a fixed one-time addition to the screenshot process and it will handle all future inputs.
Note that your current solution makes it easy for people to mess up in the future (part of writing maintainable code is also making it harder for people to mess up).

2024-07-02 22:30 UTC, fkurmannucsc commented
I know I didn't exactly follow your instructions from the comment bit I think the only way to do this is to create a separate function to remove the bubbling from all text inputs i.e. not doing it in the initializeHotkeys() function because that one can only really be called once to prevent duplicate behavior.

I hope I'm not missing something really obvious but this is the best solution I could come up with.

2024-07-03 00:43 UTC, eriq-augustine requested changes
Pretty close.

Response to your comment:
You can remove event listeners before adding them in initializeHotkeys(), thereby making it idempotent.
But what you have here works just fine.

2024-07-03 00:43 UTC, eriq-augustine commented on static/js/main.js
> +function removeKeydownSideEffects() {
I don't like this function name, it is both too specific and ambiguous.

Too specific: "removeKeydown".
We may choose another key event type (e.g. keyUp).

Ambiguous: "SideEffects".
["Side effect"](https://en.wikipedia.org/wiki/Side_effect_(computer_science)) has a very specific meaning in CS,
and what is happening here is not a CS side effect or even technically a side effect in the looser sense (it is unintentional, but not a side effect).

Mirroring your initializeHotkeys() function, maybe something like "removeHotkeysOnText()".

2024-07-03 00:43 UTC, eriq-augustine commented on static/js/main.js
> +    removeKeydownSideEffects();
Move this call inside initializeHotkeys().

It's nicer when functions deal with their own fallout.

2024-07-03 01:29 UTC, eriq-augustine approved these changes
lgtm

2024-07-03 01:30 UTC, merged